name: weatherapp
description: Weather App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  dio: ^5.1.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  retrofit: ^4.0.1
  json_annotation: ^4.7.0
  logger: ^1.3.0
  pretty_dio_logger: ^1.1.1
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  intl: ^0.18.1
  sqflite: ^2.2.8+4
  cached_network_image: ^3.2.3
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  retrofit_generator: 6.0.0+3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
